// Mock data for the entire application

export const mockMembers = [
  {
    id: 1,
    name: "João Silva",
    email: "joao.silva@email.com",
    phone: "(11) 98765-4321",
    status: "active",
    cell: "Juventude Central",
    role: "Membro",
    joinDate: "2024-01-15",
    city: "São Paulo",
    avatar: "JS"
  },
  {
    id: 2,
    name: "Maria Santos",
    email: "maria.santos@email.com",
    phone: "(11) 98765-4322",
    status: "active",
    cell: "Mulheres de Fé",
    role: "Líder",
    joinDate: "2023-06-20",
    city: "São Paulo",
    avatar: "MS"
  },
  {
    id: 3,
    name: "Pedro Costa",
    email: "pedro.costa@email.com",
    phone: "(11) 98765-4323",
    status: "inactive",
    cell: "Homens de Fé",
    role: "Membro",
    joinDate: "2023-11-10",
    city: "Guarulhos",
    avatar: "PC"
  },
  {
    id: 4,
    name: "Ana Paula",
    email: "ana.paula@email.com",
    phone: "(11) 98765-4324",
    status: "active",
    cell: "Casais Unidos",
    role: "Co-líder",
    joinDate: "2024-02-01",
    city: "São Paulo",
    avatar: "AP"
  },
  {
    id: 5,
    name: "Carlos Oliveira",
    email: "carlos.oliveira@email.com",
    phone: "(11) 98765-4325",
    status: "active",
    cell: "Juventude Central",
    role: "Membro",
    joinDate: "2024-03-12",
    city: "Osasco",
    avatar: "CO"
  },
  {
    id: 6,
    name: "Juliana Lima",
    email: "juliana.lima@email.com",
    phone: "(11) 98765-4326",
    status: "active",
    cell: "Mulheres de Fé",
    role: "Membro",
    joinDate: "2023-09-05",
    city: "São Paulo",
    avatar: "JL"
  },
  {
    id: 7,
    name: "Roberto Alves",
    email: "roberto.alves@email.com",
    phone: "(11) 98765-4327",
    status: "active",
    cell: "Homens de Fé",
    role: "Co-líder",
    joinDate: "2023-08-15",
    city: "São Caetano",
    avatar: "RA"
  },
  {
    id: 8,
    name: "Fernanda Souza",
    email: "fernanda.souza@email.com",
    phone: "(11) 98765-4328",
    status: "active",
    cell: "Adolescentes em Ação",
    role: "Líder",
    joinDate: "2024-01-20",
    city: "São Paulo",
    avatar: "FS"
  },
  {
    id: 9,
    name: "Lucas Martins",
    email: "lucas.martins@email.com",
    phone: "(11) 98765-4329",
    status: "active",
    cell: "Juventude Central",
    role: "Membro",
    joinDate: "2024-04-10",
    city: "Santo André",
    avatar: "LM"
  },
  {
    id: 10,
    name: "Beatriz Ferreira",
    email: "beatriz.ferreira@email.com",
    phone: "(11) 98765-4330",
    status: "active",
    cell: "Casais Unidos",
    role: "Membro",
    joinDate: "2023-12-05",
    city: "São Paulo",
    avatar: "BF"
  },
  {
    id: 11,
    name: "Ricardo Santos",
    email: "ricardo.santos@email.com",
    phone: "(11) 98765-4331",
    status: "active",
    cell: "Terceira Idade Feliz",
    role: "Líder",
    joinDate: "2023-07-22",
    city: "Diadema",
    avatar: "RS"
  },
  {
    id: 12,
    name: "Camila Rodrigues",
    email: "camila.rodrigues@email.com",
    phone: "(11) 98765-4332",
    status: "active",
    cell: "Mulheres de Fé",
    role: "Membro",
    joinDate: "2024-02-18",
    city: "São Paulo",
    avatar: "CR"
  },
  {
    id: 13,
    name: "Gabriel Mendes",
    email: "gabriel.mendes@email.com",
    phone: "(11) 98765-4333",
    status: "inactive",
    cell: "Adolescentes em Ação",
    role: "Membro",
    joinDate: "2023-10-30",
    city: "Mauá",
    avatar: "GM"
  },
  {
    id: 14,
    name: "Patricia Cardoso",
    email: "patricia.cardoso@email.com",
    phone: "(11) 98765-4334",
    status: "active",
    cell: "Casais Unidos",
    role: "Membro",
    joinDate: "2024-03-25",
    city: "São Paulo",
    avatar: "PC"
  },
  {
    id: 15,
    name: "Thiago Barbosa",
    email: "thiago.barbosa@email.com",
    phone: "(11) 98765-4335",
    status: "active",
    cell: "Juventude Central",
    role: "Co-líder",
    joinDate: "2023-11-14",
    city: "Guarulhos",
    avatar: "TB"
  },
  {
    id: 16,
    name: "Amanda Ribeiro",
    email: "amanda.ribeiro@email.com",
    phone: "(11) 98765-4336",
    status: "active",
    cell: "Adolescentes em Ação",
    role: "Membro",
    joinDate: "2024-01-08",
    city: "São Paulo",
    avatar: "AR"
  },
  {
    id: 17,
    name: "Felipe Gomes",
    email: "felipe.gomes@email.com",
    phone: "(11) 98765-4337",
    status: "active",
    cell: "Homens de Fé",
    role: "Membro",
    joinDate: "2023-09-20",
    city: "Osasco",
    avatar: "FG"
  },
  {
    id: 18,
    name: "Larissa Teixeira",
    email: "larissa.teixeira@email.com",
    phone: "(11) 98765-4338",
    status: "active",
    cell: "Mulheres de Fé",
    role: "Co-líder",
    joinDate: "2023-08-03",
    city: "São Paulo",
    avatar: "LT"
  },
  {
    id: 19,
    name: "Diego Pereira",
    email: "diego.pereira@email.com",
    phone: "(11) 98765-4339",
    status: "inactive",
    cell: "Juventude Central",
    role: "Membro",
    joinDate: "2024-02-10",
    city: "Santo André",
    avatar: "DP"
  },
  {
    id: 20,
    name: "Vanessa Moreira",
    email: "vanessa.moreira@email.com",
    phone: "(11) 98765-4340",
    status: "active",
    cell: "Terceira Idade Feliz",
    role: "Membro",
    joinDate: "2023-12-20",
    city: "São Caetano",
    avatar: "VM"
  }
];

export const mockEvents = [
  {
    id: 1,
    title: "Culto de Celebração",
    date: "2024-11-03",
    time: "19:00",
    duration: "2h",
    location: "Templo Principal",
    attendees: 450,
    capacity: 500,
    category: "Culto",
    status: "upcoming",
    color: "primary"
  },
  {
    id: 2,
    title: "Reunião de Célula - Juventude",
    date: "2024-11-01",
    time: "19:30",
    duration: "1h30",
    location: "Casa do João Silva",
    attendees: 22,
    capacity: 30,
    category: "Célula",
    status: "upcoming",
    color: "secondary"
  },
  {
    id: 3,
    title: "Conferência de Liderança",
    date: "2024-11-15",
    time: "09:00",
    duration: "8h",
    location: "Templo Principal",
    attendees: 85,
    capacity: 120,
    category: "Conferência",
    status: "upcoming",
    color: "accent"
  },
  {
    id: 4,
    title: "Escola Bíblica Dominical",
    date: "2024-11-03",
    time: "09:00",
    duration: "1h",
    location: "Salas de Ensino",
    attendees: 180,
    capacity: 200,
    category: "Ensino",
    status: "upcoming",
    color: "primary"
  },
  {
    id: 5,
    title: "Evangelismo na Praça",
    date: "2024-11-09",
    time: "14:00",
    duration: "3h",
    location: "Praça da Sé",
    attendees: 35,
    capacity: 50,
    category: "Evangelismo",
    status: "upcoming",
    color: "accent"
  },
  {
    id: 6,
    title: "Vigília de Oração",
    date: "2024-11-10",
    time: "22:00",
    duration: "6h",
    location: "Templo Principal",
    attendees: 120,
    capacity: 200,
    category: "Oração",
    status: "upcoming",
    color: "secondary"
  },
  {
    id: 7,
    title: "Retiro de Casais",
    date: "2024-11-16",
    time: "08:00",
    duration: "2 dias",
    location: "Chácara São José",
    attendees: 40,
    capacity: 60,
    category: "Retiro",
    status: "upcoming",
    color: "accent"
  },
  {
    id: 8,
    title: "Workshop de Louvor",
    date: "2024-11-12",
    time: "15:00",
    duration: "3h",
    location: "Sala de Música",
    attendees: 28,
    capacity: 40,
    category: "Workshop",
    status: "upcoming",
    color: "primary"
  },
  {
    id: 9,
    title: "Congresso de Jovens",
    date: "2024-11-20",
    time: "18:00",
    duration: "4h",
    location: "Ginásio Municipal",
    attendees: 350,
    capacity: 500,
    category: "Congresso",
    status: "upcoming",
    color: "secondary"
  },
  {
    id: 10,
    title: "Reunião de Ministérios",
    date: "2024-11-05",
    time: "20:00",
    duration: "2h",
    location: "Sala Administrativa",
    attendees: 25,
    capacity: 35,
    category: "Reunião",
    status: "upcoming",
    color: "primary"
  }
];
